#!/bin/sh
set -e

case "$1" in
    configure)
		USERID=`id -u www-data`
		if [ $? -eq 0 ]; then
        	chown -R root:www-data /usr/share/repoman/html
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
