#!/usr/bin/env python

from repoman.config import conf
if conf('server.daemonize'):
    from ncore.daemon import become_daemon
    become_daemon(out_log=conf('server.daemon_log'), err_log=conf('server.daemon_log'))

from wsgiref.simple_server import make_server, WSGIRequestHandler
from multiprocessing import Process
from traceback import format_exc
import sys

from repoman.wsgi import Application, StaticHandler
from repoman import repository
from repoman import buildbot

app = Application([
    ('^/repository/(?P<dist>[-\w]+)/(?P<package>[a-z0-9][a-z0-9+-.]+)/(?P<action>\w+)/*$',
        repository.PackageHandler),
    ('^/repository/(?P<dist>[-\w]+)/(?P<package>[a-z0-9][a-z0-9+-.]+)/*$',
        repository.PackageHandler),
    ('^/repository/(?P<dist>[-\w]+)/*$',
        repository.DistHandler),
    ('^/repository/*$',
        repository.RepoHandler),
    ('^/buildbot/status/(?P<buildid>[a-z0-9]{32})/*$',
        buildbot.StatusHandler),
    ('^/buildbot/tarball/(?P<buildid>[a-z0-9]{32})/*$',
        buildbot.TarballHandler),
    ('^/buildbot/(?P<gitpath>[a-z]+)/(?P<gitrepo>.+)/*$',
        buildbot.PackageHandler),
    ('^/buildbot/(?P<gitpath>[a-z]+)/*$',
        buildbot.RepoListHandler),
    ('^/(?P<path>.*)$',
        StaticHandler),
])

wsgi = WSGIRequestHandler
def address_string(self):
    return self.client_address[0]
wsgi.address_string = address_string

p = Process(target=buildbot.build_worker)
p.start()

server = make_server(conf('server.bind_address'), conf('server.bind_port'), app)

try:
    server.serve_forever()
except:
    sys.stderr.write(format_exc() + '\n')
    p.terminate()
